branches:
  only:
  - master

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-8
    packages:
    - libstdc++-8-dev

install:
    - sudo apt-get -y install clang++-8 clang-tidy-8 cmake perl
    - scripts/install_valgrind.sh
    - scripts/install_gtest.sh
    - scripts/install_ncurses.sh

script:
    - make game
    - make analyze
    - make run_tests
